### ISSUE TITLE
Issue with tag action

### ISSUE THREAD

**Issue by thrijith** [LeoColomb/wordpress-action#1]
Hi @LeoColomb, thanks for the Deploy action.

I tried using it but it isn't working as expected.

Tag action is resulting in following error.
```
refs/heads/master does not match refs/tags/*

### DECLINED Tag 18:01:11Z (21.157s)
```

Here is the current workflow.
```
workflow "Build, Test, and Publish" {
  on = "push"
  resolves = ["Publish"]
}

# Filter for a new tag
action "Tag" {
  uses = "actions/bin/filter@master"
  args = "tag"
}

action "Publish" {
  needs = "Tag"
  uses = "leocolomb/wordpress-action@master"
  env = {
    WORDPRESS_PLUGIN = "post-contributor"
  }
  secrets = ["WORDPRESS_USERNAME", "WORDPRESS_PASSWORD"]
}
```

Could you please let me know where it went wrong?

Thanks.

**Comment by LeoColomb** [comment]
Thanks for opening this issue, @thrijith!
The tag filter comes from another GitHub Action ([that one](https://github.com/actions/bin/tree/master)).
The goal of that action is to execute next actions only if the head is a tag, i.e. if the workfow is executed over a git tag.
To pass the filter you need to create a tag, then the workflow will be run on that tag.

**Comment by thrijith** [comment]
>The goal of that action is to execute next actions only if the head is a tag, i.e. if the workfow is executed over a git tag.
>To pass the filter you need to create a tag, then the workflow will be run on that tag.

After doing all the changes for workflow. I created and pushed a tag ( while on master branch ) [here](https://github.com/thrijith/post-contributor/tags)
I hope that is the correct way.
